---

- name: Download and Extract spdx-generator tool
  unarchive:
    # src: https://github.com/opensbom-generator/spdx-sbom-generator/releases/download/v0.0.15/spdx-sbom-generator-v0.0.15-linux-amd64.tar.gz
    src: "{{ release_link }}/{{ latest_version }}"
    dest: /opt/
    remote_src: yes
